name: ARM64 修改kubeadm证书默认年限

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: '请填写k8s的版本'
        required: true
        default: 'v1.18.6'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 安装go环境
      run: |
        wget https://dl.google.com/go/go1.23.4.linux-arm64.tar.gz && tar -xf go1.23.4.linux-arm64.tar.gz -C /usr/local/ && export PATH=$PATH:/usr/local/go/bin && go version

    - name: 获取k8s源码
      run: |
        wget https://github.com/kubernetes/kubernetes/archive/refs/tags/${{ github.event.inputs.k8s_version }}.zip && unzip ${{ github.event.inputs.k8s_version }}.zip  && ls

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: arm64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-arm64.tar
